---

- hosts: "{{ env }}:&swarm"
  tasks:
    - name: Install Packages
      apt: name={{ item }} state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Add Docker Apt Key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Apt Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Apt Update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker CE
      apt:
        name: docker-ce=17.03.0~ce-0~ubuntu-xenial
