---

version: "3.1"

volumes:
  postgres:
  minio:

networks:

  traefik:
    driver: overlay
    driver_opts:
      encrypted: ""

  app:
    driver: overlay
    driver_opts:
      encrypted: ""

services:

  # TRAEFIK
  traefik:
    deploy:
      placement:
        constraints:
          - node.role == manager
    image: traefik:1.2.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/peragrin/acme.json:/acme.json
      - /etc/peragrin/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
      - app

  # POSTGRESQL
  postgresql:
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.labels.postgres == true
    image: postgres:9.6.2
    networks:
      - app
    env_file: .env
    environment:
      - POSTGRES_USER=db
    volumes:
      - postgres:/var/lib/postgresql/data

  # MINIO
  minio:
    image: minio/minio
    env_file: .env
    command: server /data
    networks:
      - traefik
      - app
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:minio.{{ domain }}"
        - "traefik.frontend.passHostHeader=true"
      placement:
        constraints:
          - node.role == worker
          - node.labels.minio == true
    volumes:
      - minio:/data

  # APP
  api:
    image: registry.gitlab.com/peragrin/api:master
    networks:
      traefik:
      app:
        aliases:
          - upstream
    env_file: .env
    environment:
      - DB_NAME=app
      - DB_PORT=5432
      - DB_HOST=postgresql
      - STORE_ENDPOINT=minio.{{ domain }}
      - STORE_SECURE=true
      - APP_DOMAIN=https://app.{{ domain }}
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=peragrin_traefik"
        - "traefik.frontend.rule=Host:api.{{ domain }}"
      placement:
        constraints:
          - node.role == worker

  web-client:
    image: registry.gitlab.com/peragrin/web-client:master
    networks:
      - traefik
      - app
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=peragrin_traefik"
        - "traefik.frontend.rule=Host:app.{{ domain }}"
      placement:
        constraints:
          - node.role == worker
