defaultEntryPoints = ["http", "https"]
debug = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "josh.eppinette@peragrin.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false

[[acme.domains]]
  main = "{{ domain }}"
  sans = [
    "api.{{ domain }}",
    "app.{{ domain }}"
  ]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ domain }}"
watch = true
swarmmode = true
exposedbydefault = false
